version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: velociraptor-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:
      - ./neo4j_data_volumes/current/data:/data
      - ./neo4j_data_volumes/current/logs:/logs
      - ./neo4j_data_volumes/current/import:/var/lib/neo4j/import
      - ./neo4j_data_volumes/current/plugins:/plugins
    restart: unless-stopped

  semantic-search:
    build:
      context: .
      dockerfile: Dockerfile.semantic-search
    image: velociraptor/semantic-search:latest
    env_file:
      - .env.docker
    restart: unless-stopped
    stdin_open: true
    tty: true